# Generated by Django 2.1 on 2018-09-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mix',
            options={'verbose_name_plural': 'Mixes'},
        ),
        migrations.RenameField(
            model_name='mix',
            old_name='mixed',
            new_name='count',
        ),
    ]
