# Generated by Django 2.1 on 2018-09-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180907_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='quantity',
            field=models.FloatField(help_text='In centiliter [cL]'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='density',
            field=models.FloatField(default=100, help_text='In grams per liter [g/L]'),
        ),
    ]
