# Generated by Django 2.1 on 2018-09-13 17:13

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20180913_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='density',
            field=models.FloatField(default=1000, help_text='In grams per liter [g/L]'),
        ),
        migrations.AlterField(
            model_name='mix',
            name='image',
            field=models.ImageField(blank=True, height_field='height', max_length=200, null=True, upload_to=recipes.models.mix_upload_to, width_field='width'),
        ),
    ]
