# Generated by Django 2.1 on 2018-09-14 20:23

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_mix_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mix',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mix',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', max_length=200, null=True, upload_to=recipes.models.mix_upload_to, width_field='image_width'),
        ),
    ]
