# Generated by Django 2.1 on 2018-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_dose_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
