# Generated by Django 2.1.2 on 2018-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_mix_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_only_available_mixes', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
