# Generated by Django 2.2 on 2019-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20190406_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Empty'), (1, 'Waiting for glass'), (2, 'Serving'), (3, 'Done')], default=0),
        ),
    ]
