# Generated by Django 2.2 on 2019-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20190406_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
