# Generated by Django 2.2 on 2019-04-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20190406_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Empty'), (1, 'Waiting for glass'), (2, 'Serving'), (3, 'Done')], default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Mix')),
            ],
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
