# Generated by Django 2.2 on 2019-04-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20190406_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Empty'), (1, 'Waiting for glass'), (2, 'Serving'), (3, 'Done')], default=0),
        ),
    ]
